### ISSUE TITLE
CWP site tree icons should be using default

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/cwp#150] opened 2018-08-30 23:03 UTC
At the moment the site tree is using custom black icons.

![screen shot 2018-08-31 at 11 04 33 am](https://user-images.githubusercontent.com/24258161/44884035-bf45c180-ad0d-11e8-87ef-144f84a1c029.png)

We should change these to use the default site tree icons (which are also in the process of being updated).

Reference: https://github.com/silverstripe/silverstripe-admin/issues/574#issuecomment-411245123

PRs:
- [x] #193 
- [x] silverstripe/silverstripe-registry#55
- [x] silverstripe/recipe-content-blocks#9

**Comment by robbieaverill** [comment] 2019-01-07 10:19
I've just been looking over this with @sachajudd and the dependent issue in https://github.com/silverstripe/silverstripe-admin/issues/574#issuecomment-411245123. We can't use CSS font classes yet, so we'll need to replace the icon images in this module for now to use the new ones once they're available in core. The current page type images haven't been changed since CWP 1.0, so definitely in need of a polish!

**Comment by robbieaverill** [comment] 2019-04-04 22:42
@silverstripeux you may want to revisit this soon. Font based icons are supported in SilverStripe 4.4, which will ship in CWP 2.3 in the next quarter. We can roll these out to all supported modules that have page types. Note that there is a regression in the new font icon work: https://github.com/silverstripe/silverstripe-cms/issues/2369

**Comment by sachajudd** [comment] 2019-04-04 22:58
I have a PR up for that regression here: https://github.com/silverstripe/silverstripe-cms/pull/2391. The regression left is this issue: https://github.com/silverstripe/silverstripe-cms/issues/2368. We will only be able to get to this in early May.

**Comment by clarkepaul** [comment] 2019-04-08 00:10
@brynwhyman this would be a nice addition to CWP to get the new icons. The new icons will be available in Core so ideally we should just use them instead of having custom icons in CWP.

**Comment by brynwhyman** [comment] 2019-04-11 21:49
> this would be a nice addition to CWP to get the new icons

@clarkepaul I've added this to the upcoming release - we'll see if we can fit it in

**Comment by robbieaverill** [comment] 2019-05-08 21:44
All merged

**Closed by robbieaverill** 2019-05-08 21:44 UTC
Labels: affects/v4, change/minor, effort/easy, type/UX, type/enhancement, type/frontend
