### ISSUE TITLE
Content blocks are written three times when saving as draft

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#118] opened 2018-06-19 02:19 UTC
**CWP 2.1.x.dev**

* Create a blocks page
* Create a content block
* Change the content
* Press Save
* Go to history tab

Saving will creates two versions.

Publishing will create three versions (expected behaviour, because versioned now creates a new version for published even if its the same as the draft - right @tractorcow?)

**Comment by robbieaverill** [comment] 2018-06-19 02:50
Elemental has a bunch of places where its doing calls to `DataObject::write()` that it potentially doesn't need to, so this might not be all that surprising

**Comment by robbieaverill** [comment] 2018-06-19 03:49
Partial fix at #244 but still a problem

**Comment by NightJar** [comment] 2018-07-05 22:29
Minimum steps to recreate:

construct site:
```
    "require": {
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "^4.2",
        "dnadesign/silverstripe-elemental": "3.0.x-dev"
    },
```
Steal a couple of things from `silverstripe/recipe-content-blocks`:
`app/src/BlocksPage.php`
```
<?php

class BlocksPage extends Page
{
    private static $table_name = 'BlocksPage';

    private static $description = 'A modular page composed of content blocks';
}
```
`app/_config/contentblocks.yml`
```
---
Name: mysitecontentblocks
---
BlocksPage:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
```

🎯 load cms (pages view by default)
⌨️ "Add new" "BlocksPage" "At root level"
👉 Publish
👉 Add Content block
⌨️ Title: "One", Content: "Content element."
👉 Save
♻️  Refresh
👉 History tab
👀 One item - current version.
👉 Content tab
⌨️ Content: "Content element (a.k.a. block)."
👉 Save
♻️ Refresh
👉 History tab
👀 _Three_ versions. Expected: 2 versions.
👉 Content tab
⌨️ Content: "Content element (a.k.a. block).\n Published."
👉 Publish
♻️ Refresh
👀 _SIX_ versions. Expected: 4 (3 saves, 1 publish).

```
dnadesign/silverstripe-elemental          3.0.x-dev 2a60407 Elemental pagetype and collection of Elements
silverstripe/admin                        1.2.0-beta1       SilverStripe admin interface
silverstripe/asset-admin                  1.2.0-beta1       Asset management for the SilverStripe CMS
silverstripe/assets                       1.2.0-beta1       SilverStripe Assets component
silverstripe/campaign-admin               1.2.0-beta1       SilverStripe campaign admin interface
silverstripe/cms                          4.2.0-beta1       The SilverStripe Content Management System
silverstripe/config                       1.0.5-beta1       SilverStripe configuration based on YAML and class statics
silverstripe/errorpage                    1.2.0-beta1       ErrorPage component for SilverStripe CMS
silverstripe/framework                    4.2.0-beta1       The SilverStripe framework
silverstripe/graphql                      2.0.0-beta1       GraphQL server for SilverStripe models and other data
silverstripe/recipe-cms                   4.2.0-beta1       SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-core                  4.2.0-beta1       SilverStripe framework-only core recipe
silverstripe/recipe-plugin                1.3.0             Helper plugin to install SilverStripe recipes
silverstripe/reports                      4.2.0-beta1       Reports module for SilverStripe CMS
silverstripe/siteconfig                   4.2.0-beta1       Site wide settings administration.
silverstripe/vendor-plugin                1.3.3             Allows vendor modules to expose directories to the webroot
silverstripe/versioned                    1.2.0-beta1       SilverStripe Versioned component
silverstripe/versioned-admin              1.0.0-beta1       SilverStripe versioned admin interface
symbiote/silverstripe-gridfieldextensions 3.2.0             A collection of useful grid field components
```

At this point it's either directly `elemental`'s fault, or a core issue.
Continuing investigation.

**Comment by NightJar** [comment] 2018-07-06 00:43
**_New_ minimum steps to reproduce**
`composer create-project silverstripe/installer test ^4`
`app/src/AnThing.php`
```
<?php

use SilverStripe\ORM\DataObject;
use SilverStripe\Versioned\Versioned;

class AnThing extends DataObject
{
    private static $db = ['Title' => 'Varchar'];
    private static $has_one = ['Page' => Page::class];
    private static $extensions = [Versioned::class];
}
```
`app/src/Page.php`
```
<?php

namespace {

    use SilverStripe\CMS\Model\SiteTree;
    use SilverStripe\Forms\GridField\GridField;
    use SilverStripe\Forms\GridField\GridFieldConfig_RelationEditor;
    
    class Page extends SiteTree
    {
        private static $db = [];
        
        private static $has_many = ['Things' => AnThing::class];
        
        public function getCMSFields()
        {
            $fields = parent::getCMSFields();
            $fields->addFieldToTab(
                'Root.TheThings',
                GridField::create(
                    'Things',
                    'Things',
                    $this->Things(),
                    GridFieldConfig_RelationEditor::create()
                )
            );
            return $fields;
        }
    }
}
```
Build site.
Load CMS.
Edit Home.
The Things tab
Add An Thing
Enter a Title
Create
-> Database shows one version. ✅ (new record, first version)
Change title.
Publish.
-> Database shows three versions. ✅ (two versions created for two actions {save, publish})
Alter title.
Save.
-> Database shows five versions ❌ (two versions created for one action {save})
Alter title.
Publish.
-> Database shows seven versions ✅ (two versions created for two actions {save, publish})
Alter title.
Save.
-> Database shows nine versions ❌ (two versions created for one action {save})
do **not** alter title.
Save.
-> Database shows ten versions ✅ (one new version for one action {publish})

```
silverstripe/admin                 1.1.2   SilverStripe admin interface
silverstripe/asset-admin           1.1.2   Asset management for the SilverStripe CMS
silverstripe/assets                1.1.2   SilverStripe Assets component
silverstripe/campaign-admin        1.1.2   SilverStripe campaign admin interface
silverstripe/cms                   4.1.2   The SilverStripe Content Management System
silverstripe/config                1.0.4   SilverStripe configuration based on YAML and class statics
silverstripe/errorpage             1.1.2   ErrorPage component for SilverStripe CMS
silverstripe/framework             4.1.2   The SilverStripe framework
silverstripe/graphql               1.1.2   GraphQL server for SilverStripe models and other data
silverstripe/recipe-core           1.1.2   SilverStripe framework-only core recipe
silverstripe/recipe-plugin         1.3.0   Helper plugin to install SilverStripe recipes
silverstripe/reports               4.1.2   Reports module for SilverStripe CMS
silverstripe/siteconfig            4.1.2   Site wide settings administration.
silverstripe/vendor-plugin         1.3.3   Allows vendor modules to expose directories to the webroot
silverstripe/versioned             1.1.2   SilverStripe Versioned component
```

**Comment by robbieaverill** [comment] 2018-07-06 01:04
Cool, looks like you’ve tracked this as a core problem in https://github.com/silverstripe/silverstripe-versioned/issues/166. Can we close this as a duplicate of that for now?

**Comment by NightJar** [comment] 2018-07-06 01:05
Too fast mate!
I came here just now to do exactly that!

Closing because this is a core issue logged at: https://github.com/silverstripe/silverstripe-versioned/issues/166

**Closed by NightJar** 2018-07-06 01:05 UTC
Labels: affects/v4, change/patch, effort/hard, impact/medium, type/UX, type/bug
