### ISSUE TITLE
Sitemap Bugs

### ISSUE THREAD

**Issue by phptek** [silverstripe/cwp#44] opened 2018-02-14 01:55 UTC
I have tried a raw install (Granted not using cwp-installer) and my current project (uses 90% of cwp-installer packages, save for blog-recipe)

SitemapPage Issues:

1). src/components/js/sitemap.js uses `$('.SiteMap')` when the classname used in the `<body>` tag as of SS4 is the FQ PHP classname (Which IMO it shouldn't be, for several reasons) so the onclick action on a SiteMap Page's "+" icon doesn't even fire an AJAX request

I fixed it like this:

```
$('a.sitemap__collapse-action').on('click', function (e) {
```

2). OK, assuming these are fixed, we get a 500 error being unable to detect the correct template:

On `cwp/cwp/src/PageTypes/SitemapPageController.php:43`

From:

```
return $viewer->renderWith('SitemapNodeChildren');
```

To:

```
return $viewer->renderWith('Includes/SitemapNodeChildren');
```

I have to concede that our project has a bit of a screwy arrangement of themes (couldn't get my head around theme inheritance fast enough) but prefixing with "Includes" couldn't hurt, could it?

I worked around it for now using Injector:

```
# Temporary until #44 is fixed: 
SilverStripe\Core\Injector\Injector:
  CWP\CWP\PageTypes\SitemapPageController:
    class: 'Catalyst\TDC\Page\TDCSitemapPageController'
```

**Comment by phptek** [comment] 2018-02-14 01:58
UPDATE: Weird, issue 3 may not be one (an issue) any more...browser cache possibly..

**Comment by robbieaverill** [comment] 2018-02-14 02:29
Just a quick check - are you using the latest version of master?

**Comment by phptek** [comment] 2018-02-14 03:05
Yup:

```
#> composer info cwp/cwp
name     : cwp/cwp
descrip. : CWP features module. We strongly recommend using it for all new sites. Future features will be delivered here.
keywords : cwp, silverstripe
versions : * dev-master, 2.x-dev
type     : silverstripe-vendormodule
license  : BSD 3-Clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
source   : [git] https://github.com/silverstripe/cwp.git fc0387be3e5dd56c866f4e27b89374664fb02cda
```

**Comment by robbieaverill** [comment] 2018-02-14 03:39
Problem 1: resolved in starter-theme with https://github.com/silverstripe/cwp-starter-theme/commit/57f78c992af159ebfa3dc2ff3cae45d012e5aa11

Problem 2: Fix at #45

Thanks for reporting :)

**Comment by phptek** [comment] 2018-02-14 17:44
One final issue is that child-nodes do not expand correctly (Top-level ones are fine). Clicking a "+" toggle redirects to the page you actually wanted to expand. If you mouseover a top-level link's "+" toggle, you can see the href attr in your browser's status bar. Try mousing over the equivalent in a child node and all you see is the fragment identifier, not the path. I tried messing with the include templates but I'm finding it very hard to reason about markup + JS these days....

**Comment by robbieaverill** [comment] 2018-02-14 20:59
@phptek thanks - I can't reproduce this any more. Have you got an up to date starter theme? Also do you have any errors in the console?

**Comment by phptek** [comment] 2018-02-14 21:11
How do you get an up-to-date "starter" theme? That's the theme that you modify and customise right? And "watea" remains "as-is". Cos our "starter" theme has been customised, then there's no way to pull-in further upstream changes.

**Comment by robbieaverill** [comment] 2018-02-14 21:36
@phptek I see - perhaps you just need to copy in the changes from https://github.com/silverstripe/cwp-starter-theme/commit/57f78c992af159ebfa3dc2ff3cae45d012e5aa11

We can't help you with custom code unfortunately

**Closed** 2018-02-18 23:03 UTC
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug
