### ISSUE TITLE
A few questions about this module

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/cwp#137] opened 2018-07-09 21:34 UTC
We are using this module at the moment and I have a few questions, I hope you don't mind posting them here:

(1) why not break this module up into several ones so that you can pick and choose the items you need - e.g. blog, sitemap, event, analytics, social media, etc...? We want to use some of this module but not all of this module (e.g. we do need a blog) and that is now pretty tricky.  You could always recombine with a few recipes - right?  Is the idea that having a bit of extra code floating about not such a big deal? 

(2) the Footer Holder concept seems a bit weird.  Why use a page type to create a footer menu when there are so many more elegant solutions (e.g. simple tickbox "include in footer menu", "menu builder", etc...)?  Are we missing something in terms of how this should be used?

**Comment by robbieaverill** [comment] 2018-07-09 22:47
Hi @sunnysideup 

> why not break this module up into several ones so that you can pick and choose the items you need 

We started to do this, for example by splitting out the CWP search functionality into the CWP search module and recipe.

You don't necessarily need all of the custom page types, etc, but you could always fork and remove the bits you don't want :)

>Why use a page type to create a footer menu when there are so many more elegant solutions

You're probably right, this is an example of a relic of early versions of CWP that were designed this way. There are probably better ways to do it nowadays.

I'm going to close this for now since it's not a bug report. Thanks!

**Closed by robbieaverill** 2018-07-09 22:47 UTC

**Comment by robbieaverill** [comment] 2018-07-10 01:44
Perhaps on forum.silverstripe.org
