### ISSUE TITLE
Content block-Spell check in WYSIWYG isn't working

### ISSUE THREAD

**Issue by katieelks** [silverstripe/cwp#79] opened 2018-04-30 23:40 UTC
![spell_check](https://user-images.githubusercontent.com/778003/39611222-2419a962-4faa-11e8-88d1-8292934dede1.png)

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-spellcheck/pull/36
- [ ] #80

**Comment by robbieaverill** [comment] 2018-04-30 23:40
Are you able to check whether the silverstripe/spellcheck module is installed, and which version it is?

**Comment by katieelks** [comment] 2018-04-30 23:43
yup it's version 2.0.0

**Comment by robbieaverill** [comment] 2018-05-03 22:30
Debugging on CWP: `{"error":"Not supported locale"}`

**Comment by robbieaverill** [comment] 2018-05-03 22:45
The error is caused by trying to spellcheck in en_US locale which isn't enabled by default. This happens when TinyMCE says the language is "en" which then gets converted to the default English locale which is en_US. CWP only allows en_NZ and mi_NZ by default.

In this instance we should ensure that "en" defaults to "en_NZ", particularly for CWP which is primarily used in New Zealand English.

The second problem here is how we handle errors that come from the silverstripe/spellcheck module. Note that this isn't a regression from 1.x in how the errors are handled, but because the response from the spellcheck module has a 400 header code, TinyMCE treats these errors as problems resolving the backend service, which is why we see "The spelling service was not found." What we need to do here is return a valid 200 header code with the same response format as noted above, which would then render "Not supported locale" as an error message. This would be immensely more useful to CMS editors than what we see in this issue.

**Comment by robbieaverill** [comment] 2018-05-03 23:25
Pull requests to fix added to the issue description

**Closed** 2018-05-04 02:57 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/bug

**Comment by katieelks** [comment] 2018-05-04 03:00
Hey team, thanks for fixing this! just so I understand will the fix be in the next release of CWP2? or will the current version be updated to include this fix?

**Comment by robbieaverill** [comment] 2018-05-04 03:00
@katieelks it will be included in the CWP 2.0 recipe when it is stable and ready for production use (it's not at the moment)
