### ISSUE TITLE
only run tinyMCE code when you need to

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/cwp#210] opened 2019-06-25 22:53 UTC
I am wondering why this code:

https://github.com/silverstripe/cwp/blob/1f7ba0c0ee566329e981cdbf1609f3c94da4aa44/_config.php

Is in the global space.  Why not run that whenever an HTML editor is created? 

In the past, we have also hacked this to say that if the request url starts with /admin/, we run it.

**Comment by robbieaverill** [comment] 2019-06-25 22:59
Closing as a duplicate of https://github.com/silverstripe/cwp/issues/139 =)

**Closed by robbieaverill** 2019-06-25 22:59 UTC

**Comment by sunnysideup** [comment] 2019-06-25 23:14
;-)))) sorry! I did feel a little deja vu... ;-)
